export const conseils = [
  {
    slug: "que-faire-en-cas-de-fuite",
    title: "Que faire en cas de fuite d'eau",
    description: "Couper l'eau, protéger les biens, appeler un plombier à Caluire ou Lyon. Gestes utiles avant l'arrivée de PLOMB'ACTIV.",
    h1: "Que faire en cas de fuite d'eau",
    body: [
      "Une fuite n'attend pas. L'objectif est de limiter l'eau, pas de bricoler un collier de fortune si vous n'êtes pas à l'aise.",
      "1. Trouvez la vanne d'arrêt du logement ou le compteur. Fermez-la. Si vous ne la trouvez pas, descendez en cave ou regardez près de la rue, puis appelez.",
      "2. Coupez l'électricité dans la pièce inondée si l'eau approche les prises.",
      "3. Essuyez, surélevez les cartons, photographiez pour l'assurance.",
      "4. Appelez PLOMB'ACTIV au 06 67 44 79 29. Dites si c'est une fuite active, un plafond, un WC, un ballon.",
      "On isole, on cherche, on répare. Pas de délai magique affiché : on se déplace depuis Caluire.",
    ],
  },
  {
    slug: "couper-eau-urgence",
    title: "Comment couper l'eau en urgence",
    description: "Où trouver la vanne d'arrêt, le compteur, la vanne d'immeuble. Gestes avant l'arrivée du plombier à Lyon ou Caluire.",
    h1: "Comment couper l'eau en urgence",
    body: [
      "La vanne d'arrêt du logement est souvent sous l'évier, dans un placard technique, ou près du compteur individuel.",
      "Tournez dans le sens des aiguilles d'une montre jusqu'à blocage franc. Ne forcez pas une vanne grippée : vous pouvez casser le tube.",
      "En immeuble, le compteur général n'est pas toujours accessible. Prévenez le gardien ou le voisin si l'eau continue.",
      "Chaudière gaz : une fois l'eau coupée, laissez l'appareil hors gel selon la notice. Signalez-nous si la chaudière s'est mise en sécurité.",
      "Ensuite : 06 67 44 79 29.",
    ],
  },
  {
    slug: "wc-bouche",
    title: "WC bouché : que faire avant le plombier",
    description: "Gestes utiles (et ceux à éviter) quand un WC est bouché à Lyon ou Caluire. PLOMB'ACTIV débouchage et remplacement.",
    h1: "WC bouché : que faire",
    body: [
      "Arrêtez de tirer la chasse. Chaque chasse supplémentaire peut faire déborder.",
      "Une ventouse bien posée sur la cuvette, quelques mouvements lents, parfois suffisent. Pas de produits chimiques agressifs si vous allez appeler un plombier : ça irrite les voies et n'aide pas le débouchage mécanique.",
      "Si l'eau remonte dans la douche ou l'évier en même temps, le bouchon est plus loin (colonne). N'insistez pas.",
      "PLOMB'ACTIV débouchage et, si le WC est HS, remplacement (photos avant / après sur le site).",
    ],
  },
  {
    slug: "chauffe-eau-ne-chauffe-plus",
    title: "Chauffe-eau qui ne chauffe plus : diagnostic",
    description: "Plus d'eau chaude : thermostat, résistance, groupe de sécurité, arrivée. Quand remplacer le ballon à Caluire ou Lyon.",
    h1: "Chauffe-eau qui ne chauffe plus",
    body: [
      "Vérifiez le disjoncteur du ballon et le groupe de sécurité (il doit goutter un peu au réchauffage, pas fuir en continu).",
      "Pas d'eau du tout : vanne d'arrivée. Eau froide seulement : thermostat, résistance, ou ballon en fin de vie.",
      "Un cumulus entartré ou percé se change. On pose mural ou au sol, Atlantic ou équivalent, raccord PER ou cuivre.",
      "Plusieurs clients ont noté PLOMB'ACTIV 5 étoiles précisément pour un chauffe-eau. Appelez le 06 67 44 79 29.",
    ],
  },
  {
    slug: "odeur-gaz-chaudiere",
    title: "Odeur de gaz près de la chaudière",
    description: "Que faire en cas d'odeur de gaz à Lyon ou Caluire : aérer, couper, appeler. PLOMB'ACTIV dépannage chaudière gaz.",
    h1: "Odeur de gaz près de la chaudière",
    body: [
      "Aérez, n'actionnez pas d'interrupteur, n'allumez pas une flamme. Si l'odeur est nette, sortez et appelez le 04 72 11 13 13 (Urgence sécurité gaz GRDF) en plus du plombier.",
      "Coupez l'arrivée gaz si vous savez où est le robinet, sans forcer.",
      "PLOMB'ACTIV intervient sur chaudière gaz (brûleur, organe, étanchéité). On n'est pas le service d'urgence réseau GRDF : les deux numéros peuvent se succéder.",
      "Atelier Caluire : 06 67 44 79 29.",
    ],
  },
  {
    slug: "ballon-eau-chaude-fuit",
    title: "Ballon d'eau chaude qui fuit",
    description: "Groupe de sécurité qui goutte, fuite sous le cumulus, flaque au sol. Gestes et remplacement à Caluire et Lyon.",
    h1: "Ballon d'eau chaude qui fuit",
    body: [
      "Un groupe de sécurité goutte un peu au réchauffage : c'est normal. Un filet continu ou une flaque sous la cuve : ce n'est plus du fonctionnement.",
      "Coupez l'arrivée d'eau du ballon et l'électrique. Posez une bassine. Ne videz pas à l'aveugle un ballon encore chaud sans précaution.",
      "Souvent : groupe HS, raccord, ou cuve percée (changement de l'appareil). Photos de poses Atlantic sur le site.",
      "PLOMB'ACTIV, 06 67 44 79 29.",
    ],
  },
  {
    slug: "mitigeur-qui-goutte",
    title: "Mitigeur ou robinet qui goutte",
    description: "Robinet qui goutte à Lyon ou Caluire : cartouche, siège, remplacement. PLOMB'ACTIV plomberie sanitaire.",
    h1: "Mitigeur qui goutte",
    body: [
      "Un goutte-à-goutte use le siège et fait exploser la facture d'eau. Coupez l'eau au point d'eau ou à la vanne d'arrêt.",
      "Souvent une cartouche céramique. Parfois le corps du mitigeur est mort : remplacement.",
      "On intervient cuisine, salle de bains, douche. Devis avant si ce n'est pas une urgence.",
      "06 67 44 79 29, atelier à Caluire-et-Cuire.",
    ],
  },
  {
    slug: "radiateur-froid",
    title: "Radiateur froid alors que la chaudière tourne",
    description: "Radiateur froid, purger, vase d'expansion, vanne. Chauffagiste PLOMB'ACTIV à Caluire et Lyon.",
    h1: "Radiateur froid, chaudière en marche",
    body: [
      "Un seul radiateur froid : souvent air (purge) ou vanne coincée. Tous froids : chaudière, circulateur, pression.",
      "Purgez avec un clé, bassine sous la vis. Si de l'eau sort sans air et que ça reste froid, arrêtez de purger.",
      "Pression chaudière trop basse : on regarde ensemble, sans vous faire bricoler le vase d'expansion à l'aveugle.",
      "Dépannage gaz : 06 67 44 79 29.",
    ],
  },
] as const;
