import { photos } from "./photos";

export type VillePage = {
  slug: string;
  name: string;
  cp: string;
  driveMin: string;
  housing: string;
  localIssue: string;
  extra: string;
  quartiers: string[];
  neighbors: { slug: string; label: string }[];
  image: string;
  imageAlt: string;
  aliases?: string[];
};

export const villes: VillePage[] = [
  {
    slug: "villeurbanne",
    name: "Villeurbanne",
    cp: "69100",
    driveMin: "15 à 25 min (Gratte-Ciel, Cusset, Charpennes, Tonkin)",
    housing: "Immeubles 60-80, copros, colonnes collectives, salles de bains compactes.",
    localIssue: "Colonnes lentes, siphons, ballons en fin de vie, fuites en pied de colonne.",
    extra: "Collée à Lyon 3e et 6e : même tournée possible qu'un chantier caluirard. Pas une page copiée d'un réseau national.",
    quartiers: ["Gratte-Ciel", "Cusset", "Charpennes", "Tonkin", "Croix-Luizet", "Buers"],
    neighbors: [
      { slug: "croix-rousse", label: "Croix-Rousse" },
      { slug: "vaulx-en-velin", label: "Vaulx-en-Velin" },
    ],
    image: photos.reseaux,
    imageAlt: "Réseaux plomberie type copropriété, intervention vers Villeurbanne",
  },
  {
    slug: "rillieux-la-pape",
    name: "Rillieux-la-Pape",
    cp: "69140",
    driveMin: "10 à 20 min depuis Saint Clair (montée ou périphérique nord)",
    housing: "Mix pavillons Crépieux / collectifs Ville Nouvelle, beaucoup de chaudières gaz.",
    localIssue: "Groupes de sécurité, cumulus tartre, fuites sous évier, WC dans les collectifs des années 70.",
    extra: "Rillieux est la commune la plus rapide au nord de l'atelier. Crépieux-la-Pape, Semailles, Alagniers, Les Cailloux : on confirme le quartier au téléphone pour le trajet.",
    quartiers: ["Rillieux centre", "Crépieux-la-Pape", "Semailles", "Alagniers", "Velette", "Les Cailloux", "Ville Nouvelle"],
    neighbors: [
      { slug: "sathonay-camp", label: "Sathonay-Camp" },
      { slug: "miribel", label: "Miribel" },
      { slug: "crepieux-la-pape", label: "Crépieux-la-Pape" },
    ],
    image: photos.cumulus,
    imageAlt: "Ballon d'eau chaude, intervention fréquente à Rillieux-la-Pape",
  },
  {
    slug: "crepieux-la-pape",
    name: "Crépieux-la-Pape",
    cp: "69140",
    driveMin: "10 à 15 min, collé à Caluire par la montée",
    housing: "Maisons et petits collectifs, plus villageois que la Ville Nouvelle de Rillieux.",
    localIssue: "Vannes d'arrêt, fuites cave, ballons garage, évacuations pavillon.",
    extra: "Crépieux n'est pas une commune : c'est le quartier sud de Rillieux, le plus proche de Saint Clair. On y passe souvent le même matin qu'un chantier caluirard.",
    quartiers: ["Crépieux centre", "vers Caluire", "vers Semailles"],
    neighbors: [
      { slug: "rillieux-la-pape", label: "Rillieux-la-Pape" },
      { slug: "saint-clair", label: "Saint-Clair" },
    ],
    image: photos.heroWork,
    imageAlt: "Intervention plomberie sous évier, secteur Crépieux-la-Pape",
    aliases: [],
  },
  {
    slug: "vaulx-en-velin",
    name: "Vaulx-en-Velin",
    cp: "69120",
    driveMin: "20 à 35 min selon le pont",
    housing: "Collectifs, logements rénovés par vagues, salles d'eau compactes.",
    localIssue: "Évacuations PVC, WC, fuites en pied de colonne.",
    extra: "On confirme si le chantier est tout au bout de la commune. Pas de promesse d'arrivée en 30 minutes.",
    quartiers: ["Centre", "Pré de l'Herpe", "Mas du Taureau", "La Soie"],
    neighbors: [
      { slug: "villeurbanne", label: "Villeurbanne" },
      { slug: "decines-charpieu", label: "Décines" },
    ],
    image: photos.wc,
    imageAlt: "Sanitaire et évacuation, débouchage WC",
  },
  {
    slug: "neuville-sur-saone",
    name: "Neuville-sur-Saône",
    cp: "69250",
    driveMin: "15 à 25 min le long de la Saône",
    housing: "Maisons de village, caves, cuivre ancien, chaudières en sous-sol.",
    localIssue: "Caves humides, regards, fuites sur arrivée, groupes de sécurité.",
    extra: "Axe nord : même tournée qu'Albigny ou Rochetaillée si les deux créneaux tiennent.",
    quartiers: ["Centre bourg", "quais de Saône", "cités pavillonnaires"],
    neighbors: [
      { slug: "rochetaillee-sur-saone", label: "Rochetaillée" },
      { slug: "fontaines-sur-saone", label: "Fontaines-sur-Saône" },
    ],
    image: photos.chalumeau,
    imageAlt: "Brasage cuivre, maisons de Neuville-sur-Saône",
  },
  {
    slug: "miribel",
    name: "Miribel",
    cp: "01700",
    driveMin: "20 à 30 min, pont de Miribel",
    housing: "Pavillonnaire, lotissements, ballons en garage, vides sanitaires.",
    localIssue: "Calcaire, groupes de sécurité, canalisations hors gel.",
    extra: "Côté Ain, trajet réaliste en journée depuis Caluire. On le dit si le créneau glisse.",
    quartiers: ["Centre", "Les Echets (selon trajet)", "lotissements nord"],
    neighbors: [
      { slug: "rillieux-la-pape", label: "Rillieux-la-Pape" },
      { slug: "neyron", label: "Neyron" },
    ],
    image: photos.ballonMural,
    imageAlt: "Chauffe-eau mural en pavillon, secteur Miribel",
  },
  {
    slug: "neyron",
    name: "Neyron",
    cp: "01700",
    driveMin: "20 à 30 min vers l'Ain",
    housing: "Pavillons, R+1, ballons, chaudières murales.",
    localIssue: "Hors gel, regards jardin, mitigeurs, cumulus.",
    extra: "Petite commune entre Miribel et Rillieux : on y va si le trajet du jour tient, sans page clone.",
    quartiers: ["Bourg", "vers canal de Miribel"],
    neighbors: [
      { slug: "miribel", label: "Miribel" },
      { slug: "rillieux-la-pape", label: "Rillieux" },
    ],
    image: photos.ballonMural,
    imageAlt: "Pose chauffe-eau, secteur Neyron",
  },
  {
    slug: "decines-charpieu",
    name: "Décines-Charpieu",
    cp: "69150",
    driveMin: "25 à 40 min par l'est lyonnais",
    housing: "Pavillons et collectifs, salles de bains à rénover.",
    localIssue: "WC, PER, chaudières murales.",
    extra: "Souvent couplé avec Meyzieu la même après-midi si les deux devis sont confirmés.",
    quartiers: ["Centre", "Grand Large", "vers Meyzieu"],
    neighbors: [{ slug: "meyzieu", label: "Meyzieu" }, { slug: "vaulx-en-velin", label: "Vaulx-en-Velin" }],
    image: photos.wcAvantApres,
    imageAlt: "Remplacement de WC, chantier PLOMB'ACTIV",
  },
  {
    slug: "meyzieu",
    name: "Meyzieu",
    cp: "69330",
    driveMin: "30 à 45 min",
    housing: "Maisons, garages avec ballon, jardins et regards.",
    localIssue: "Ballons, hors gel, chaudières gaz.",
    extra: "Limite est de tournée : le 06 67 44 79 29 sert à dire si on passe, pas à promettre une heure.",
    quartiers: ["Centre", "Porte du Dauphiné", "ZAC"],
    neighbors: [{ slug: "decines-charpieu", label: "Décines" }],
    image: photos.chaudiere,
    imageAlt: "Chaudière gaz, dépannage",
  },
  {
    slug: "saint-priest",
    name: "Saint-Priest",
    cp: "69800",
    driveMin: "30 à 45 min sud-est",
    housing: "Collectifs et lots 90, salles de bains à reprendre.",
    localIssue: "Évacuations, mitigeurs, fuites sous baignoire.",
    extra: "Limite sud-est. On y va, on confirme le délai réel.",
    quartiers: ["Centre", "Bel-Air", "Manissieux"],
    neighbors: [{ slug: "decines-charpieu", label: "Décines" }],
    image: photos.degatEaux,
    imageAlt: "Recherche de fuite et dégât des eaux",
  },
  {
    slug: "sathonay-camp",
    name: "Sathonay-Camp",
    cp: "69580",
    driveMin: "8 à 15 min au nord de Caluire",
    housing: "Collectifs et maisons, beaucoup de logements récents + gros bâti ancien militaire reconverti.",
    localIssue: "Groupes de sécurité, mitigeurs, chauffe-eau muraux, colonnes d'immeuble.",
    extra: "Sathonay-Camp est collé à Caluire : c'est du voisinage, pas une « zone Grand Lyon » abstraite. Même artisan, même numéro.",
    quartiers: ["Centre", "cités", "vers Rillieux"],
    neighbors: [
      { slug: "sathonay-village", label: "Sathonay-Village" },
      { slug: "rillieux-la-pape", label: "Rillieux" },
      { slug: "fontaines-sur-saone", label: "Fontaines" },
    ],
    image: photos.interventionLyon,
    imageAlt: "Matériel prêt pour intervention Sathonay-Camp",
  },
  {
    slug: "sathonay-village",
    name: "Sathonay-Village",
    cp: "69580",
    driveMin: "10 à 18 min",
    housing: "Village, pavillons, caves, réseaux parfois mixtes cuivre / PER.",
    localIssue: "Fuites cave, vannes grippées, chaudières gaz.",
    extra: "Plus résidentiel que Sathonay-Camp. On y enchaîne souvent après un passage Camp ou Fontaines.",
    quartiers: ["Bourg", "hameaux"],
    neighbors: [
      { slug: "sathonay-camp", label: "Sathonay-Camp" },
      { slug: "fontaines-sur-saone", label: "Fontaines-sur-Saône" },
    ],
    image: photos.chalumeau,
    imageAlt: "Brasage cuivre, habitat type Sathonay-Village",
  },
  {
    slug: "fontaines-sur-saone",
    name: "Fontaines-sur-Saône",
    cp: "69270",
    driveMin: "10 à 20 min le long de la Saône",
    housing: "Maisons de berges, caves, chaudières en sous-sol, collectifs modestes.",
    localIssue: "Humidité cave, fuites arrivée, ballons, regards.",
    extra: "Entre Caluire et Rochetaillée. Trajet naturel depuis Saint Clair, sans plateforme ni standard 24h/24 affiché.",
    quartiers: ["Centre", "quais", "vers Rochetaillée"],
    neighbors: [
      { slug: "rochetaillee-sur-saone", label: "Rochetaillée" },
      { slug: "sathonay-camp", label: "Sathonay-Camp" },
      { slug: "collonges-au-mont-d-or", label: "Collonges" },
    ],
    image: photos.degatEaux,
    imageAlt: "Humidité et recherche de fuite, secteur Fontaines-sur-Saône",
  },
  {
    slug: "collonges-au-mont-d-or",
    name: "Collonges-au-Mont-d'Or",
    cp: "69660",
    driveMin: "10 à 20 min (montée ou quai)",
    housing: "Maisons de coteau, vides sanitaires, cuivre, chaudières gaz.",
    localIssue: "Pentes, accès cave, calcaire, groupes de sécurité.",
    extra: "Monts d'Or : on connaît les rues étroites. Le délai dépend du stationnement, on le dit au 06 67 44 79 29.",
    quartiers: ["Bourg", "coteaux", "vers Saint-Cyr"],
    neighbors: [
      { slug: "saint-cyr-au-mont-d-or", label: "Saint-Cyr" },
      { slug: "fontaines-sur-saone", label: "Fontaines" },
      { slug: "cuire", label: "Cuire" },
    ],
    image: photos.artisan,
    imageAlt: "Intervention cuivre sous ballon, Monts d'Or",
  },
  {
    slug: "saint-cyr-au-mont-d-or",
    name: "Saint-Cyr-au-Mont-d'Or",
    cp: "69450",
    driveMin: "15 à 25 min dans les monts",
    housing: "Pavillonnaire de coteau, grandes maisons, chaufferies, réseaux longs.",
    localIssue: "Pression, vases d'expansion, fuites encastrées, ballons volume.",
    extra: "Pas le même habitat qu'un T3 à Villeurbanne. On prévoit le matériel après l'appel, pas un kit universel « 30 minutes ».",
    quartiers: ["Bourg", "coteaux", "vers Saint-Didier"],
    neighbors: [
      { slug: "saint-didier-au-mont-d-or", label: "Saint-Didier" },
      { slug: "collonges-au-mont-d-or", label: "Collonges" },
    ],
    image: photos.chaudiere,
    imageAlt: "Chaudière gaz, habitat Monts d'Or",
  },
  {
    slug: "saint-didier-au-mont-d-or",
    name: "Saint-Didier-au-Mont-d'Or",
    cp: "69370",
    driveMin: "15 à 25 min",
    housing: "Maisons, parfois piscine / arrosage, chaudières condensation.",
    localIssue: "Hors gel, vannes jardin, ECS, radiateurs.",
    extra: "Toujours Caluire comme base. On ne joue pas les 24h/24 nationaux : on se déplace quand le créneau est vrai.",
    quartiers: ["Bourg", "vers Écully", "coteaux"],
    neighbors: [
      { slug: "saint-cyr-au-mont-d-or", label: "Saint-Cyr" },
      { slug: "saint-romain-au-mont-d-or", label: "Saint-Romain" },
      { slug: "ecully", label: "Écully" },
    ],
    image: photos.chaudiere,
    imageAlt: "Dépannage chaudière, Saint-Didier-au-Mont-d'Or",
  },
  {
    slug: "saint-romain-au-mont-d-or",
    name: "Saint-Romain-au-Mont-d'Or",
    cp: "69270",
    driveMin: "15 à 25 min",
    housing: "Village Saône, caves, cuivre, parfois stilligoutte berges.",
    localIssue: "Caves, arrivées, chaudières anciennes.",
    extra: "Petite commune : une page honnête vaut mieux que dix textes identiques de plateforme.",
    quartiers: ["Bourg", "quais"],
    neighbors: [
      { slug: "couzon-au-mont-d-or", label: "Couzon" },
      { slug: "collonges-au-mont-d-or", label: "Collonges" },
    ],
    image: photos.chalumeau,
    imageAlt: "Réseau cuivre, Saint-Romain-au-Mont-d'Or",
  },
  {
    slug: "couzon-au-mont-d-or",
    name: "Couzon-au-Mont-d'Or",
    cp: "69270",
    driveMin: "15 à 25 min le long de la Saône",
    housing: "Village, mitoyennetés, caves, colonnes serrées.",
    localIssue: "Évacuations anciennes, fuites mitoyennes, WC.",
    extra: "Entre Rochetaillée et Collonges. Accès parfois étroit : on le note à l'appel.",
    quartiers: ["Bourg", "quais"],
    neighbors: [
      { slug: "rochetaillee-sur-saone", label: "Rochetaillée" },
      { slug: "saint-romain-au-mont-d-or", label: "Saint-Romain" },
    ],
    image: photos.wc,
    imageAlt: "Sanitaires et évacuation, Couzon-au-Mont-d'Or",
  },
  {
    slug: "rochetaillee-sur-saone",
    name: "Rochetaillée-sur-Saône",
    cp: "69270",
    driveMin: "12 à 22 min",
    housing: "Village, maisons de caractère, caves, chauffage gaz.",
    localIssue: "Fuites cave, chaudières, ballons.",
    extra: "Sur l'axe Caluire → Neuville. Idéal à glisser entre deux chantiers de berge.",
    quartiers: ["Bourg", "vers Fontaines", "vers Neuville"],
    neighbors: [
      { slug: "fontaines-sur-saone", label: "Fontaines-sur-Saône" },
      { slug: "neuville-sur-saone", label: "Neuville" },
      { slug: "couzon-au-mont-d-or", label: "Couzon" },
    ],
    image: photos.cumulus,
    imageAlt: "Ballon ECS, Rochetaillée-sur-Saône",
  },
  {
    slug: "ecully",
    name: "Écully",
    cp: "69130",
    driveMin: "20 à 35 min par le Valvert / périphérique",
    housing: "Maisons, résidences, campus, chaudières et splits.",
    localIssue: "Entretien chaudière, ECS, robinetterie, fuites encastrées.",
    extra: "Ouest lyonnais : on y va, on dit si le créneau du jour tient. Pas de page clone « plombier Écully 24h/24 ».",
    quartiers: ["Centre", "Le Grand Large", "vers Tassin"],
    neighbors: [{ slug: "saint-didier-au-mont-d-or", label: "Saint-Didier" }, { slug: "cuire", label: "Cuire" }],
    image: photos.clim,
    imageAlt: "Climatisation et chauffage, secteur Écully",
  },
  {
    slug: "croix-rousse",
    name: "Croix-Rousse",
    cp: "69004",
    driveMin: "10 à 20 min depuis Saint Clair (montée ou quais)",
    housing: "Immeubles canuts, colonnes, salles d'eau étroites, commerces en rez-de-chaussée.",
    localIssue: "Colonnes, fuites plafond voisin, WC, compteurs dans cages d'escalier.",
    extra: "Lyon 4e est le quartier le plus naturel depuis Caluire. Un avis Google du site décrit une fuite WC en commerce, intervention discrète.",
    quartiers: ["Grand Côte", "Boulevard", "Gros Caillou", "Clos Jouve"],
    neighbors: [
      { slug: "cuire", label: "Cuire" },
      { slug: "saint-clair", label: "Saint-Clair" },
      { slug: "villeurbanne", label: "Villeurbanne" },
    ],
    image: photos.reseaux,
    imageAlt: "Réseaux en immeuble, type Croix-Rousse",
    aliases: ["Lyon 4e"],
  },
  {
    slug: "saint-clair",
    name: "Saint-Clair",
    cp: "69300",
    driveMin: "L'atelier est ici : 130 Grande rue de Saint Clair",
    housing: "Mix immeubles et maisons, quais, accès rapides Lyon 6e / Caluire bourg.",
    localIssue: "Urgences du quartier, ballons, fuites, débouchage : souvent le plus court délai réel de la tournée.",
    extra: "Ce n'est pas un quartier inventé pour le SEO : c'est l'adresse SIRET. Vous joignez l'atelier qui se déplace, pas un call center.",
    quartiers: ["Grande rue", "quais", "vers Cuire", "vers le pont"],
    neighbors: [
      { slug: "cuire", label: "Cuire" },
      { slug: "montessuy", label: "Montessuy" },
      { slug: "croix-rousse", label: "Croix-Rousse" },
    ],
    image: photos.interventionLyon,
    imageAlt: "Départ intervention PLOMB'ACTIV depuis Saint-Clair",
  },
  {
    slug: "cuire",
    name: "Cuire",
    cp: "69300",
    driveMin: "5 à 12 min dans Caluire",
    housing: "Caluire historique, immeubles et maisons, salles de bains des années 70-90.",
    localIssue: "Mitigeurs, chasses, colonnes, chaudières murales.",
    extra: "Cuire, c'est Caluire, pas Lyon. Beaucoup cherchent « plombier Cuire » : même atelier Saint-Clair, même ligne 06 67 44 79 29.",
    quartiers: ["Cuire-le-Bas", "vers le bourg", "vers la Saône"],
    neighbors: [
      { slug: "saint-clair", label: "Saint-Clair" },
      { slug: "montessuy", label: "Montessuy" },
      { slug: "collonges-au-mont-d-or", label: "Collonges" },
    ],
    image: photos.wcAvantApres,
    imageAlt: "Remplacement sanitaire, quartier Cuire",
  },
  {
    slug: "montessuy",
    name: "Montessuy",
    cp: "69300",
    driveMin: "8 à 15 min dans Caluire",
    housing: "Collectifs et résidences, parkings, colonnes, ballons collectifs ou individuels.",
    localIssue: "Groupes de sécurité, siphons, fuites parties communes (après accord syndic si besoin).",
    extra: "Haut de Caluire, vers Rillieux. Utile si vous tapez « plombier Montessuy » plutôt que Caluire.",
    quartiers: ["résidences", "vers Vassieux", "vers Sathonay"],
    neighbors: [
      { slug: "sathonay-camp", label: "Sathonay-Camp" },
      { slug: "cuire", label: "Cuire" },
      { slug: "rillieux-la-pape", label: "Rillieux" },
    ],
    image: photos.cumulus,
    imageAlt: "Ballon ECS en résidence, Montessuy",
  },
];

export function villeBySlug(slug: string) {
  return villes.find((v) => v.slug === slug);
}

export function pathForZoneName(name: string): string | null {
  if (name === "Caluire-et-Cuire") return "/plombier-caluire-et-cuire";
  if (name === "Lyon 4e") return "/plombier/croix-rousse";
  if (name.startsWith("Lyon")) return "/plombier-lyon";
  const v = villes.find((x) => x.name === name || x.aliases?.includes(name));
  return v ? `/plombier/${v.slug}` : null;
}

export const footerCityLinks = [
  { href: "/plombier-caluire-et-cuire", label: "Plombier Caluire (69300)" },
  { href: "/plombier/saint-clair", label: "Saint-Clair" },
  { href: "/plombier/cuire", label: "Cuire" },
  { href: "/plombier/rillieux-la-pape", label: "Rillieux-la-Pape (69140)" },
  { href: "/plombier/sathonay-camp", label: "Sathonay-Camp" },
  { href: "/plombier/fontaines-sur-saone", label: "Fontaines-sur-Saône" },
  { href: "/plombier/collonges-au-mont-d-or", label: "Collonges" },
  { href: "/plombier/croix-rousse", label: "Croix-Rousse" },
  { href: "/zone-intervention", label: "Toute la zone" },
];
